# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
FROM docker.io/eclipse-temurin:21-jdk-jammy
RUN apt update
RUN apt install --yes maven git python3
# TODO Remove usage of /home/distro/ because the home folder is root.
VOLUME /root/Documents/
VOLUME /root/.ssh/
VOLUME /root/.m2
WORKDIR /root/Documents/projects/net.splitcells.martins.avots.support.system/public/net.splitcells.network.distro
ENTRYPOINT ["/usr/bin/sh"]
CMD ["-c", "/root/Documents/projects/net.splitcells.martins.avots.support.system/public/net.splitcells.network.distro/bin/build.on.server"]